#!/usr/bin/python3
"""The function raises a name exception with a message."""

def raise_exception_msg(message=""):

    raise NameError(message)
